/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./screens/**/*.{js,jsx,ts,tsx}"
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#003824",
        "inverse-on-surface": "#313032",
        "on-secondary-fixed-variant": "#92002a",
        "secondary-fixed-dim": "#ffb2b7",
        "on-background": "#e5e1e4",
        "on-surface": "#e5e1e4",
        "on-tertiary-fixed": "#002113",
        "surface": "#131315",
        "on-primary-fixed": "#23005c",
        "primary-container": "#a078ff",
        "on-primary-container": "#340080",
        "secondary-container": "#b50036",
        "surface-dim": "#131315",
        "primary": "#d0bcff",
        "surface-container": "#201f21",
        "surface-container-lowest": "#0e0e10",
        "outline": "#958ea0",
        "on-error-container": "#ffdad6",
        "outline-variant": "#494454",
        "background": "#131315",
        "surface-tint": "#d0bcff",
        "inverse-surface": "#e5e1e4",
        "surface-bright": "#39393b",
        "tertiary-container": "#00a572",
        "error": "#ffb4ab",
        "tertiary": "#4edea3",
        "on-primary": "#3c0091",
        "surface-container-low": "#1c1b1d",
        "on-tertiary-container": "#00311f",
        "tertiary-fixed-dim": "#4edea3",
        "primary-fixed": "#e9ddff",
        "primary-fixed-dim": "#d0bcff",
        "secondary-fixed": "#ffdadb",
        "on-secondary": "#67001b",
        "inverse-primary": "#6d3bd7",
        "surface-container-high": "#2a2a2c",
        "on-tertiary-fixed-variant": "#005236",
        "on-primary-fixed-variant": "#5516be",
        "on-secondary-container": "#ffc2c4",
        "error-container": "#93000a",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-highest": "#353437",
        "on-secondary-fixed": "#40000d",
        "on-error": "#690005",
        "on-surface-variant": "#cbc3d7",
        "secondary": "#ffb2b7",
        "surface-variant": "#353437"
      }
    },
  },
  plugins: [],
}
